#!/usr/bin/env ruby

require 'pathname'
require 'fileutils'

vim_dir = Pathname(__FILE__).parent.realpath
bundles = (vim_dir + "bundles.txt").read.split("\n")

url = ARGV.shift or raise "no URL given"

unless bundles.include?(url)
  bundles << url
  (vim_dir + "bundles.txt").open("w") {|f| f << bundles.join("\n")}
end


dir = url.split('/').last.sub(/\.git$/, '')
puts "unpacking #{url} into #{vim_dir + "bundle" + dir}"
`git clone --depth 1 #{url} #{vim_dir + "bundle" + dir}`
FileUtils.rm_rf(vim_dir + "bundle" + dir + ".git")
FileUtils.rm_f(vim_dir + "bundle" + dir + ".gitmodules")

case dir
when "command-t"
  Dir.chdir(vim_dir + "bundle/command-t/ruby/command-t") do
    system "ruby extconf.rb"
    system "make"
  end
end
