#!/usr/bin/env ruby

require 'pathname'
require 'fileutils'

vim_dir = Pathname(__FILE__).parent.realpath

url = ARGV.shift or raise "no URL given"

bundles = (vim_dir + "bundles.txt").read.split("\n")
unless bundles.include?(url)
  bundles << url
  system "echo #{url} >> #{vim_dir + "bundles.txt"}"
end


dir = url.split('/').last.sub(/\.git$/, '')
puts "unpacking #{url} into #{vim_dir + "bundle" + dir}"
`git clone --depth 1 #{url} #{vim_dir + "bundle" + dir}`
FileUtils.rm_rf(vim_dir + "bundle" + dir + ".git")
FileUtils.rm_f(vim_dir + "bundle" + dir + ".gitmodules")
