#!/usr/bin/env ruby

git_bundles = %w[
  git://github.com/tpope/vim-pathogen.git
  git://github.com/altercation/vim-colors-solarized.git
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

Dir.chdir(bundles_dir) do

  puts "trashing everything (lookout!)"
  Dir["*"].each {|d| FileUtils.rm_rf d }

  git_bundles.each do |url|
    dir = url.split('/').last.sub(/\.git$/, '')
    puts "unpacking #{url} into #{dir}"
    `git clone --depth 1 #{url} #{dir}`
    FileUtils.rm_rf(File.join(dir, ".git"))
    FileUtils.rm_f(File.join(dir, ".gitmodules"))
  end

  end
end
