#! /bin/zsh

bindkey -v "^[[3~" delete-char
bindkey -v "^[[5~" backward-word
bindkey -v "^[[6~" forward-word

bindkey -v "^[[A" history-beginning-search-backward
bindkey -v "^[[B" history-beginning-search-forward

bindkey -v "^A" beginning-of-line
bindkey -v "^E" end-of-line
bindkey -v "^K" kill-line
bindkey -v "^L" clear-screen
bindkey -v "^R" history-incremental-search-backward
bindkey -v "^U" kill-whole-line
bindkey -v "^V" quoted-insert
bindkey -v "^W" backward-kill-word

bindkey -v "^N" down-history
bindkey -v "^P" up-history

bindkey -v "^[H" run-help
bindkey -v "^[h" run-help

#bindkey -e
#bindkey "^[[B" down-line-or-history
#bindkey "^[[A" up-line-or-history
#bindkey "^[[D" backward-char
#bindkey "^[[C" forward-char
#bindkey "^R" history-incremental-search-backward
#bindkey "^F" history-incremental-search-forward
#bindkey "^E" vi-end-of-line
#bindkey "^A" vi-beginning-of-line
#bindkey "^W" vi-forward-blank-word
#bindkey "^B" vi-backward-blank-word
#bindkey '\e[3~' delete-char
#bindkey '\e[1~' beginning-of-line
#bindkey '\e[4~' end-of-line
#bindkey '\eOH' beginning-of-line
#bindkey '\eOF' end-of-line
