#! /bin/zsh
#
# vi-mode colour changing
#   http://www.zsh.org/mla/users/2006/msg01196.html

setopt prompt_subst
autoload colors
colors

rst="%{%b%s%u$reset_color%}"
bgc="%{%(?.$rst.%S)%}"

function lprompt {
    local col1 col2 ch1 ch2
    col1="%{$fg[black]%}"
    col2="%{$fg[green]%}"
    ch1="${col1}["
    ch2="${col1}]"

    local git_b git_s col_b col_s
    git_b='$(get_git_prompt_info '%b')'
    git_s='$(get_git_prompt_info '%s')'
    col_b="%{$fg[green]%}"
    col_s="%{$fg[red]%}"

    PROMPT="\
$bgc$ch1\
$col_b$git_b\
$col_s$git_s\
$bgc$col2%B%1~%b\
$ch2$rst \
$col2%#$rst "
}


if [ $UID -eq 0 ]; then
    PROMPT="$bgc%{%B$fg[blue]%}[%{$fg[red]%}%n@%m%{$fg[blue]%}]$rst "
    RPROMPT="$rst%{$fg[red]%}(%B%{$fg[red]%}%~%b%{$fg[red]%})$rst "
else
    lprompt
    RPROMPT="$rst%{$fg[yellow]%}(%n@%m:%~)$rst"
fi

unset rst bgc

# precmd is executed before each prompt
# this updates title bar before prompt is printed
precmd() {
  [[ -t 1 ]] || return
  case $TERM in
      *xterm*|rxvt|(dt|k|E)term) print -Pn "\e]2;$USER@$HOSTNAME:%~\a"
      ;;
  esac
}
